<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\projects.props" />

	<PropertyGroup>
		<TargetFramework>$(CCSPredictTargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="33.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CCSPredict.Models\CCSPredict.Models.csproj" />
  </ItemGroup>

</Project>
